export const CREATE_STOCK = 'CREATE_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';

export const CREATE_FLOW = 'CREATE_FLOW';
export const UPDATE_FLOW = 'UPDATE_FLOW';
export const DELETE_FLOW = 'DELETE_FLOW';

export const CREATE_SIMULATION = 'CREATE_SIMULATION';
export const UPDATE_SIMULATION = 'UPDATE_SIMULATION';
export const DELETE_SIMULATION = 'DELETE_SIMULATION';

export const FETCH_PROJECT = 'FETCH_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
